#!/usr/bin/env node
const addData = require('./add_data')
const fetch = require('node-fetch')

const getAndAddData = entry => {
  const { subreddit } = entry
  return getSubbredditData(subreddit)
  .then(data => {
    entry.subscribers = data.subscribers
    entry.lang = data.lang
    console.log(entry)
  })
  .catch(err => {
    if (err.statusCode === 403 && err.body.reason === 'private') {
      entry.private = true
      console.log(entry)
      return
    }
    if (err.statusCode === 404 && err.body.reason === 'banned') {
      entry.banned = true
      console.log(entry)
      return
    }
    throw err
  })
}

const headers = {
  // A User-Agent is required
  'User-Agent': 'wikidata-scripting (https://github.com/maxlath/wikidata-scripting)'
}

const getSubbredditData = async subreddit => {
  const { data } = await fetch(`https://www.reddit.com/r/${subreddit}/about.json`, { headers }).then(res => res.json())
  return data
}

addData({ label: 'reddit', getAndAddData })
