#!/usr/bin/env node
const addData = require('./add_data')
const breq = require('bluereq')

const getAndAddData = entry => {
  const { subreddit } = entry
  return getSubbredditData(subreddit)
  .then(data => {
    entry.subscribers = data.subscribers
    entry.lang = data.lang
    console.log(entry)
  })
  .catch(err => {
    if (err.statusCode === 403 && err.body.reason === 'private') {
      entry.private = true
      console.log(entry)
      return
    }
    if (err.statusCode === 404 && err.body.reason === 'banned') {
      entry.banned = true
      console.log(entry)
      return
    }
    throw err
  })
}

const getSubbredditData = subreddit => {
  return breq.get({
    url: `https://www.reddit.com/r/${subreddit}/about.json`,
    headers: {
      // A User-Agent is required
      'User-Agent': 'wikidata-scripting (https://github.com/maxlath/wikidata-scripting)'
    }
  })
  .get('body')
  .get('data')
}

addData({ label: 'reddit', getAndAddData })
