#!/usr/bin/env node

const wdLang = require('wikidata-lang')
const path = require('path')
const { addScriptHeader, fixStatementId, buildCommand, addDone } = require('../common')
const [ statementsPath, channelName, date ] = process.argv.slice(2)

const list = require(path.resolve(statementsPath))
  .map(entry => {
    entry.statementId = fixStatementId(entry.statement_id)
    return entry
  })

addScriptHeader()

const buildCommands = entry => {
  const { statementId, subscribers, lang } = entry
  const channel = entry[channelName]
  if (subscribers || lang) {
    // Padding entries commands
    console.log()
    console.log(`echo '${channelName}: ${channel}'`)
  }

  if (subscribers) {
    buildCommand('add-qualifier', statementId, 'P3744', subscribers)
    buildCommand('add-reference', statementId, 'P813', date)
  }

  if (lang && wdLang.byCode[lang]) {
    const langWdId = wdLang.byCode[lang].wd
    buildCommand('add-qualifier', statementId, 'P407', langWdId)
  }
}

list.forEach(buildCommands)
addDone()
