#!/usr/bin/env bash
# Using wd create-entity from wikidata-cli
# See https://github.com/maxlath/wikidata-cli/blob/master/docs/write_operations.md#wd-create-entity

wd create-entity ./http_status_code.js 100 'Continue' '6.2.1'
wd create-entity ./http_status_code.js 101 'Switching Protocols' '6.2.2'
wd create-entity ./http_status_code.js 200 'OK' '6.3.1'
wd create-entity ./http_status_code.js 201 'Created' '6.3.2'
wd create-entity ./http_status_code.js 202 'Accepted' '6.3.3'
wd create-entity ./http_status_code.js 203 'Non-Authoritative Information' '6.3.4'
wd create-entity ./http_status_code.js 204 'No Content' '6.3.5'
wd create-entity ./http_status_code.js 205 'Reset Content' '6.3.6'
wd create-entity ./http_status_code.js 300 'Multiple Choices' '6.4.1'
wd create-entity ./http_status_code.js 400 'Bad Request' '6.5.1'
wd create-entity ./http_status_code.js 402 'Payment Required' '6.5.2'
wd create-entity ./http_status_code.js 405 'Method Not Allowed' '6.5.5'
wd create-entity ./http_status_code.js 406 'Not Acceptable' '6.5.6'
wd create-entity ./http_status_code.js 408 'Request Timeout' '6.5.7'
wd create-entity ./http_status_code.js 409 'Conflict' '6.5.8'
wd create-entity ./http_status_code.js 411 'Length Required' '6.5.10'
wd create-entity ./http_status_code.js 413 'Payload Too Large' '6.5.11'
wd create-entity ./http_status_code.js 414 'URI Too Long' '6.5.12'
wd create-entity ./http_status_code.js 415 'Unsupported Media Type' '6.5.13'
wd create-entity ./http_status_code.js 417 'Expectation Failed' '6.5.14'
wd create-entity ./http_status_code.js 426 'Upgrade Required' '6.5.15'
wd create-entity ./http_status_code.js 500 'Internal Server Error' '6.6.1'
wd create-entity ./http_status_code.js 501 'Not Implemented' '6.6.2'
wd create-entity ./http_status_code.js 502 'Bad Gateway' '6.6.3'
wd create-entity ./http_status_code.js 504 'Gateway Timeout' '6.6.5'
wd create-entity ./http_status_code.js 505 'HTTP Version Not Supported' '6.6.6'
