#!/usr/bin/env node

const wdLang = require('wikidata-lang')

const list = require('./subreddit_claims.json')
  .map(entry => {
    var [ id, ...hash ] = entry.statement_hash.split(/-/)
    hash = hash.join('-')
    entry.statementHash = `${id}$${hash}`
    return entry
  })

console.log('#!/usr/bin/env sh')
console.log('set -eu')

const buildCommands = entry => {
  const { subreddit, statementHash, subscribers, lang } = entry
  if (subscribers || lang) {
    // Padding entries commands
    console.log()
    console.log(`echo 'subreddit: ${subreddit}'`)
  }

  if (subscribers) {
    buildCommand('add-qualifier', statementHash, 'P3744', subscribers)
    buildCommand('add-reference', statementHash, 'P813', '2018-05-06')
  }

  if (lang && wdLang.byCode[lang]) {
    const langWdId = wdLang.byCode[lang].wd
    buildCommand('add-qualifier', statementHash, 'P2439', langWdId)
  }
}

const buildCommand = (cmd, statementHash, property, value) => {
  console.log(`echo '${statementHash}' ${property} ${value}`)
  console.log(`wd ${cmd} '${statementHash}' ${property} ${value} | jd success`)
}

list.forEach(buildCommands)
console.log('echo done')
